### ISSUE TITLE
CMake error when building Multi View H5 Data Reader Operation

### ISSUE THREAD

**Issue by cvfish** [lmb-freiburg/demon#11]
When I was trying to run cmake .. to create makefile.
I ge the following error:
-------------------------------------------------------------------------------------------------------------------
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1888 (message):
  Could not extract tarball filename from url:

    https://sourceforge.net/projects/half/files/latest/download?source=files
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  multivih5datareaderop/CMakeLists.txt:55 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/mnt/work/Rui/demon/build/CMakeFiles/CMakeOutput.log".
-------------------------------------------------------------------------------------------------------------------
Any suggestions for how to solve this?

**Comment by benjaminum** [comment]
Hi,

the CMakeLists.txt was not compatible with the requested cmake minimum version (3.5.1).
Can you try the latest commit?

**Comment by cvfish** [comment]
Hi,

This fixed the problem and I managed to compile the code.
By the way, could you share the traing data as well, I guess I could only download the test data using the code provided in datasets folder. I've finished the training code myself and would like to replicate the results in the paper by training from scratch.

Thanks

**Comment by benjaminum** [comment]
There is now a script for downloading training data ```datasets/download_traindata.sh```
