### ISSUE TITLE
trying to run with webcam

### ISSUE THREAD

**Issue by rnunziata** [lmb-freiburg/demon#14]
I've been trying to run this with a webcam and have been getting very odd segment faults in tensorflow.  I was wondering if you have tried anything like this.  

the basic code loop is:

img1 = Image.open(os.path.join(examples_dir,'sculpture2.png'))
img2 = Image.open(os.path.join(examples_dir,'sculpture1.png'))
video = cv2.VideoCapture('/home/rjn/data/videos/city.mp4')

while(True):

    ok, buf = video.read()  
    buf = cv2.cvtColor(buf,cv2.COLOR_BGR2RGB)
    img2 = Image.fromarray(buf)
      *
      *
      *
   img1 = img2.copy()

```

**Comment by benjaminum** [comment]
Hi,

we have tried our network with a live camera stream from a Asus Xtion, but did not encounter any problems.
We used Tensorflow version 1.1.
We did not use OpenCV for image capture.

**Comment by rnunziata** [comment]
Thank you ... can you tell me what use used for capture, like openNI....or was it a native to Asus Xiton?

**Comment by rnunziata** [comment]
I found this solution ...
```
import pygame
import pygame.camera
from pygame.locals import *
cam = pygame.camera.Camera("/dev/video0",(640,480))
cam.start()
xx = cam.get_image()
xx = pygame.surfarray.array3d(xx)
img1 = Image.fromarray(xx)
```
