### ISSUE TITLE
need example for instrinsic cropping

### ISSUE THREAD

**Issue by rnunziata** [lmb-freiburg/demon#15]
Could you give an example on how to use the intrinsics to crop and image as stated in example. Not sure how to proceed.

**Comment by sampepose** [comment]
This is how I've been doing this:

Assume your data contains an image with width W, height H, focal lengths fx, fy.
Demon assumptions: width 256, height 192, (normalized) focal lengths 0.89115971, 1.18821287.

We can find the crop dimensions H' x W' from the relationship between focal length and image dimensions:
(0.89115971)(256) = (fx)(W')
(1.18821287)(192) = (fy)(H')

Make sure you normalize your fx, fy values (e.g., fx_norm = fx / W).

You can then resize this cropped image to the required 192 x 256 dimensions.

Best,
Sam

**Comment by rnunziata** [comment]
Thank  you

**Comment by harishannavajjala** [comment]
I have a question. After getting the crop dimension H' and W', I am wondering from which side of the original image should I crop this new one. And what if the object that I want to calculate distance to is lost after cropping? 
Thanks.

**Comment by sampepose** [comment]
You can crop anywhere in the image (center crop, random crop, whatever). Crop so the object is still in the image.

**Comment by harishannavajjala** [comment]
Thanks !!

**Comment by benjaminum** [comment]
The normalized intrinsic parameters we trained DeMoN on are 
```
K = (0.89115971  0           0.5)
    (0           1.18821287  0.5)
    (0           0           1  )
```
To adjust the focal length of your image, you scale the image such that the normalized focal lengths for the x and y dimension match (0.8911 and 1.1882). This is what @sampepose described in the second comment.

The principal point is exactly in the image center (0.5, 0.5). This means you should crop with this point as the center.

I hope this helps.
