### ISSUE TITLE
3d Coordinate System

### ISSUE THREAD

**Issue by sampepose** [lmb-freiburg/demon#16]
Hello!

From the sculpture example, I was able to deduce that the network is predicting egomotion in a coordinate system where +x points left, +y points up, +z points backwards. Is this correct? If so, I'm curious why this system was chosen. I'm not sure if there's a "standard", I just noticed that vkitti uses +x right, +y down, +z forward.

Best,
Sam

**Comment by benjaminum** [comment]
Hi,

we use the same system as vkitti with +y pointing down.
The camera visualizations have a +x and +y indicator.

best
Benjamin

**Comment by sampepose** [comment]
OK, so it is the same as vkitti: +x right, +y down, +z forward

Here's the R,t I get from the sample:
R: [[-0.02286783  0.246608    0.06226137]]
t: [[-0.97007942 -0.05802078  0.20590135]]

<img width="746" alt="screenshot 2017-09-01 10 58 41" src="https://user-images.githubusercontent.com/1855931/29981955-8da1da4c-8f04-11e7-819c-4d6286fb41b6.png">

If predicted egomotion is from frame 1 to frame 2, then why is it predicting negative x translation? From the images it looks like motion to the right, so isn't the coord system **+x left**?

**Comment by sampepose** [comment]
It looks like DeMoN is using a left-handed system with _+x left_, +y down, +z forward. vkitti uses a right-handed system with _+x right_, +y down, +z forward.

**Comment by benjaminum** [comment]
We use a right-handed coordinate system.
The x component of t is negative because we predict the world to camera transformation for the second camera.

X_cam2 = R*X_world + t

you can compute the position of the second camera relative to the first (and relative to the world) with

C_2 = -R^T * t

**Comment by sampepose** [comment]
OK, so in the paper when it says:
"We represent the relative pose of the second camera with r, t ∈ R3"
This means the pose relative to the world, not relative to the first camera?

**Comment by sampepose** [comment]
Followup questions:

1. When training, is loss defined on the predicted extrinsic R,t or on the pose R',t' (t' = -R^T * t, R' = R^T)?
2. Translation is normalized: is this extrinsic t or pose t'?

**Comment by benjaminum** [comment]
The loss is defined on the predicted extrinsics.
t is normalized.

**Comment by sampepose** [comment]
Thanks, Benjamin!
