### ISSUE TITLE
scale of depth map output

### ISSUE THREAD

**Issue by Smallha61109** [lmb-freiburg/demon#17]
I'm currently using rgbd_dataset_freiburg1_xyz as input of the example code. However, the output of the depth map prediction is so dark that i cant even see the architecture of the scene comparing to the ground truth provided by the dataset. Is the output depth map of the example code inverted? or it is the actual depth? also if i wish to compare the depth map to the ground truth, i will need to scale up the output of the example, how can i obtain the scale between the output and the ground truth?

**Comment by zhz218** [comment]
hi,
the output depth is scaled so that the translation is normalized. There is no perfect solution to scale it back. But we could try using the function 'compute_depth_scale_factor' in demon/python/depthmotionnet/evaluation/metrics.py  to get the scale between the output depth and the depth_gt

**Comment by Smallha61109** [comment]
thanks a lot!
