### ISSUE TITLE
How the testing model is trained?

### ISSUE THREAD

**Issue by pengwangucla** [lmb-freiburg/demon#2]
Hi Just wonder what kind of data the release model is trained on ? 

Is it also possible to have other models about your prediction of different scenes ? Or you use the same model for both indoor and outdoor images ? 

Thanks

**Comment by benjaminum** [comment]
There is only one model, which has been trained on the combination of data sets mentioned in the paper.
We do not finetune for specific settings, because we wanted to make the network as general as possible.

**Comment by pengwangucla** [comment]
Then, can you share the list of testing scenes in sun3d for evaluation ? 
Thanks

**Comment by benjaminum** [comment]
We use the following sequences for testing on sun3d:
```
brown_cogsci_2/brown_cogsci_2
brown_cogsci_8/brown_cogsci_8
harvard_tea_2/hv_tea2_2
mit_32_g725/g725_1
harvard_corridor_lounge/hv_lounge1_2
brown_cogsci_6/brown_cogsci_6
hotel_florence_jx/florence_hotel_stair_room_all
mit_46_6conf/bcs_floor6_conf_1
mit_w85h/h2_1
harvard_c10/hv_c10_2
brown_cs_3/brown_cs3
mit_w85g/g_0
mit_46_6lounge/bcs_floor6_long
brown_cs_7/brown_cs7
harvard_c4/hv_c4_1
harvard_robotics_lab/hv_s1_2
```
