### ISSUE TITLE
Regarding building the code on windows

### ISSUE THREAD

**Issue by vrsb2006** [lmb-freiburg/demon#21]
I generated solution file with cmake and tried building the code with visual studio (2010, 2012, 2013), but I am getting some errors:

```
Error	1	error MSB6006: "cmd.exe" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	webp

Error	2	error D8021: invalid numeric argument '/Wabi-tag'	E:\Vijay Bhardwaj\github repos\demon-master-new\lmbspecialops\build\multivih5datareaderop\cl	multivih5datareaderop
```

When I looked at the output window, it shows that

```
'CFLAGS' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 9009.
```

Another line says:

`cl : Command line error D8021: invalid numeric argument '/Wabi-tag'`

Can you help me out with this??

**Comment by benjaminum** [comment]
We tried building the code on windows but without any success.

The problem is that the tensorflow binary distribution does not come with the header files (We tried with tensorflow version 1.1).
To us it is also not clear how to build an external op library on windows with the tensorflow source distribution.

I think you need at least VS 2015 because of some C++11 features of Eigen.

Do you build tf on windows from the source distribution?

**Comment by vrsb2006** [comment]
We build tensorflow using native pip installation. I don't think that there is an option to install tf from source distribution on windows.

**Comment by ialhashim** [comment]
I was able to run it on Windows (Win 10, Visual Studio 2017, x64). 

I tried to use the provided CMake but eventually I had to manually created a new VS project with CUDA support and added the source files for the 'lmbspecialops' library. 

You also need to download the latest 'Eigen' repo and the library 'https://github.com/google/nsync'. The two external requirements were built from their sources (i.e. libwebp and libwebp).

You can find all the produced binaries in this shared folder (the main file is lmbspecialops.dll):
https://drive.google.com/drive/folders/1X7QNRzW8cybOdqLVy7tOZ9d26kUtlPWD

**Comment by vrsb2006** [comment]
Hi @ialhashim
 
Many Thanks :)

**Comment by sarathprasad000** [comment]
@ialhashim Hi Hashim, The binaries you have mentioned in the path **https://drive.google.com/drive/folders/1X7QNRzW8cybOdqLVy7tOZ9d26kUtlPWD** is missing, as the directory itself is not there. Can u kindly help us here. If the files are still there can we find a way to share it.
