### ISSUE TITLE
DeMoN's output format of relative poses

### ISSUE THREAD

**Issue by kevin0932** [lmb-freiburg/demon#28]
Hi, thanks for such an interesting work and making DeMoN open source.

I have a question regarding the output format of the relative poses predicted in the example.py file. It is clear that translation is a normalised unit vector with 3 elements. But for the rotation prediction, it is also a 3-element vector. What are these values? How does the vector represent the rotation, as mentioned in the paper " The rotation r = θv is an angle axis representation with angle θ and axis v". I just want to convert it to a rotation matrix. Would you please share more details? Thanks a lot!

**Comment by benjaminum** [comment]
Thank you for your interest in our work.

You can find a function for converting the angle axis to a rotation matrix in helpers.py

https://github.com/lmb-freiburg/demon/blob/3f15d1ae89395546c9941d5d20dbd861f6511554/python/depthmotionnet/helpers.py#L37

**Comment by kevin0932** [comment]
@benjaminum Thanks a lot for your information!
