### ISSUE TITLE
trying to run demon against a set of video images

### ISSUE THREAD

**Issue by rnunziata** [lmb-freiburg/demon#29]
I am trying to run demon against a set of  images I extracted from a video passing them into  bootstrap_net.eval. The depth images I get back are not smooth  from one image to the next but have a lot of inconsistency between  pairs.  The project web site has a video of a road with a bicyclist that looks like it was webcam or video.  I  normalize the depth images but this did not help.  How was the project video made?

**Comment by benjaminum** [comment]
We normalize the individual depth images to the gray value range [0..255]. There is no temporal normalization.

**Comment by rnunziata** [comment]
Ah...I see what I was doing to get odd results...I was trying to used monocular stream...but even if disparity is good between images the depth image is still inconsistent due the changing baseline between the images.
