### ISSUE TITLE
Does the scaling factor need to be trained?

### ISSUE THREAD

**Issue by thbupt** [lmb-freiburg/demon#3]
I think the scaling factor can be trained like rotation and translation, because the true scaling factor can be obtained by normalizing translation when training, is it right?  But in the DeMoN paper, it seems the scale is only trained together with the inverse depth.

**Comment by benjaminum** [comment]
The scaling factor predicted by the network does not correspond to the true scale of the scene, which is unknown.
We predict this factor to allow the network to adjust the scale of the depth values such that they are compatible with the unit length motion vector.
The architecture can also be trained without the scale factor, but connecting the ends of the motion and depth predicting branches with this factor improved the results.

**Comment by thbupt** [comment]
@benjaminum Thanks a lot.
