### ISSUE TITLE
How to get the depth scale factor?

### ISSUE THREAD

**Issue by jackkwok** [lmb-freiburg/demon#33]
In the paper, it states one of output of the fully connected layers is a depth scale factor s. The scale factor s relates the scale of the depth values to the camera motion.  Ref: Figure 3 in the paper.

Looking at the example code and then the source code, I am unable to figure out how I can get the scale factor value.  What am I missing?  Any help appreciated.

**Comment by benjaminum** [comment]
The returned depth map is already scaled and there is usually no need to access this value.

You can add the scale value to the outputs here
https://github.com/lmb-freiburg/demon/blob/73e6d0d9fc514bb30d4c64c61cf18778f330954b/python/depthmotionnet/networks_original.py#L175

by adding
````'predict_scale': self.netDM2_result['predict_scale'],````

**Comment by jackkwok** [comment]
Ben, thank you for your clarification.  I didn't realize the final depth output is already scaled.
