### ISSUE TITLE
Problem running own trained model

### ISSUE THREAD

**Issue by ialhashim** [lmb-freiburg/demon#35]
After around 10 days of training, the script generates the snapshot-250000.data-00000-of-00001 of the refine stage. However, plugging these newly computed weights to the provided example.py script I am getting errors starting with `Not found: Key netDM1/motion_conv1/kernel not found in checkpoint...`:

![](https://i.imgur.com/G7leoDp.jpg)

The only suspicious thing I saw during training is lots of warnings on empty queues or something like that.. but these seem to go away after a couple of stages of training.

**Comment by benjaminum** [comment]
Hi,
the v2 model is slightly different and does not directly work with the networks_original.py and blocks_original.py that are imported in the example.

I will try to upload the networks.py for the v2 tomorrow.

These warnings just indicate that data reading is sometimes too slow.

**Comment by benjaminum** [comment]
I pushed the example code for running v2 models 7419af97efd4a29bf63ac0c0a4455eb1ccf06e08

**Comment by ialhashim** [comment]
Thanks for the update. It seems to be working with my learned weights. 

There are some differences in the output, but its hard to tell if due to the missing dataset. One apparent thing is that the depths computed with v2 seem to be closer to the camera.
