### ISSUE TITLE
Batched Inference

### ISSUE THREAD

**Issue by t-fi** [lmb-freiburg/demon#43]
Hello,

Is there a simple way to apply DeMoN to batches of images? Recent GPUs have plenty of memory and inference could be sped up by spending less time moving data around. There is a hardcoded batch size of 1, for example [here ff](https://github.com/lmb-freiburg/demon/blob/73e6d0d9fc514bb30d4c64c61cf18778f330954b/python/depthmotionnet/networks_original.py#L35). So just pushing batches of data into DeMoN does not work, sadly.

I am wondering how complex the required changes are. Are there any implementation details that forbid batched inference? Maybe you can give some hints about where non trivial changes are neccessary

Thanks

**Comment by benjaminum** [comment]
Batched inference is possible.
The code can be easily adapted; see 646ef6d56c81eb7cfd03124c2b94ec192230ead6 .

**Comment by t-fi** [comment]
Works like a charm, thanks a lot!
