### ISSUE TITLE
symbol not found for lmbspecialops

### ISSUE THREAD

**Issue by hlzz** [lmb-freiburg/demon#45]
I try to follow the readme but cannot get it right. I am using tensorflow 1.4.0 with python 3.5.2, on ubuntu 16.04, here is the error message for python3:

> demon_venv tianwei@tianwei:~/Documents/Projects/demon/examples$ python3
> Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import lmbspecialops
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/tianwei/Documents/Projects/demon/lmbspecialops/python/lmbspecialops.py", line 30, in <module>
>     lmbspecialopslib = tf.load_op_library(_lib_path)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /home/tianwei/Documents/Projects/demon/lmbspecialops/build/lib/lmbspecialops.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceENS_11StringPieceEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
> >>> 
>

**Comment by hlzz** [comment]
It works fine for building lmbspecialops.so

**Comment by hlzz** [comment]
> demon_venv tianwei@tianwei:~/Documents/Projects/demon/lmbspecialops/build/lib$ ldd lmbspecialops.so 
> 	linux-vdso.so.1 =>  (0x00007ffeeca37000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5fee2c3000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5fee0bf000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5fedeb7000)
> 	libtensorflow_framework.so => /usr/local/lib/python3.5/dist-packages/tensorflow/libtensorflow_framework.so (0x00007f5fed067000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5fecce5000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5fec9dc000)
> 	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f5fec7ba000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5fec5a4000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5fec1da000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f5fee9bc000)
> 	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f5fe982a000)
> 	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f5fe89ad000)
> 	libcudnn.so.6 => /usr/local/cuda/lib64/libcudnn.so.6 (0x00007f5fdf44b000)
> 	libcufft.so.8.0 => /usr/local/cuda/lib64/libcufft.so.8.0 (0x00007f5fd65fd000)
> 	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f5fd2694000)
> 	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f5fd242e000)
> 	libnvidia-fatbinaryloader.so.384.90 => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.384.90 (0x00007f5fd21dc000)
> 

It seems to me that lmbspecialops.so have linked the correct libraries?

**Comment by benjaminum** [comment]
Which cmake version do you use?
Can you try a more recent version like 3.7 or later?
Many seem to have problems with the default cmake on ubuntu 16.04.

If that does not solve the problem check if the paths to tensorflow are correct.
From the output you posted it looks like tensorflow is installed outside of the virtualenv.

**Comment by hlzz** [comment]
cmake 3.7.1 works like a charm. Thanks a lot for your help.
