### ISSUE TITLE
How to use your project creating new dataset and training  the new dataset

### ISSUE THREAD

**Issue by JackHenry1992** [lmb-freiburg/demon#5]
Hello, thanks for your sharing with demon.

I have already run your evaluation.py successfully, and result shows your method very  effective.

Now I want to **create a new dataset(such as rgbd slam download from tum) and train this new dataset** use your project, what should I do?

_**Could you give whole source code of training**_ ?

_**Could you give list of rgbd-slam dataset which you used for training and dataset select code**_ ?

Thanks again !

**Comment by benjaminum** [comment]
We will give the source code for training, but I cannot say when it will be ready.
The original training code was written for caffe and we want to make sure that everything works.

We used the following rgbd-slam sequences for testing:
```
rgbd_dataset_freiburg2_flowerbouquet
rgbd_dataset_freiburg2_metallic_sphere
rgbd_dataset_freiburg3_teddy
rgbd_dataset_freiburg1_desk
rgbd_dataset_freiburg2_360_hemisphere
rgbd_dataset_freiburg2_rpy
```

The training sequences are 
```
rgbd_dataset_freiburg1_plant
rgbd_dataset_freiburg1_teddy
rgbd_dataset_freiburg2_coke
rgbd_dataset_freiburg2_dishes
rgbd_dataset_freiburg2_flowerbouquet_brownbackground
rgbd_dataset_freiburg2_metallic_sphere2
rgbd_dataset_freiburg3_cabinet
rgbd_dataset_freiburg3_large_cabinet
rgbd_dataset_freiburg1_360
rgbd_dataset_freiburg1_desk2
rgbd_dataset_freiburg1_room
rgbd_dataset_freiburg2_360_kidnap
rgbd_dataset_freiburg2_desk
rgbd_dataset_freiburg2_large_no_loop
rgbd_dataset_freiburg2_large_with_loop
rgbd_dataset_freiburg3_long_office_household
rgbd_dataset_freiburg1_xyz
rgbd_dataset_freiburg1_rpy
rgbd_dataset_freiburg2_xyz
```
