### ISSUE TITLE
Cmake and Make errors

### ISSUE THREAD

**Issue by InomnipotentComedy** [lmb-freiburg/demon#54]
Thank you for the awesome work. We want to build the project but there are some problems shown blow. We operated in line with your instructions (In the screenshots, we have used pew while it didn't show the virtual name at front of terminal sometimes, but this didn't impact the process of build). When we use cmake, there are some problems displayed in the images.

![3e104524d8fc04bd2b00bbc75dc0ad17](https://user-images.githubusercontent.com/27001875/46259610-38535700-c50e-11e8-919a-129f6f35a468.png)
![b936ba2c39a15f42ded2019b17537c9a](https://user-images.githubusercontent.com/27001875/46259612-42755580-c50e-11e8-8d69-84e6d4ce4a43.png)

When ignoring the cmake error and  making the makefile, the situation is same to issue #47[https://github.com/lmb-freiburg/demon/issues/47](url).

It took several days to find clues, but in vein. Thank you very much for some advice.

**Comment by InomnipotentComedy** [comment]
> I also had same problem and I solved it. All you need it's new cmake version with manual compile like this
> "./bootstrap --system-curl
> make
> sudo make install
> "
> And I see this is problem with import tensorflow because you need to
> set (PYTHON_EXECUTABLE /usr/bin/python3)
> in lmbspecialops/src/CMakeLists.txt
> Cmake found another version of Python
> first of all try to add it nearly 39 line. It's help me

Thank you very much. I followed your instruction and cmake & make successfully, although there are some warning.
But I encountered another problem. When I tried to  python the example.py,  tensorflow cannot be imported. Then I tested a simple demo and I found that if I operate on `pew`, the module would miss.
I don't know whether someone encountered this problem.

**Comment by efyphil** [comment]
If you want to use pew environment you must to install all libraries like tensorflow, cython etc in that environment like this : pip3 install tensorflow-gpu 
Or maybe just try python3 example.py

**Comment by InomnipotentComedy** [comment]
> If you want to use pew environment you must to install all libraries like tensorflow, cython etc in that environment like this : pip3 install tensorflow-gpu
> Or maybe just try python3 example.py

I tried as your advice, but the example is still not tested successfully. The errors are shown below. I've searched some solutions which are not helpful.

![default](https://user-images.githubusercontent.com/27001875/46345034-ac5c3f00-c675-11e8-84d3-a5934515fb59.png)

Sorry for trouble you. If it is convenient,  please give me more instruction. Thank you very much.

**Comment by efyphil** [comment]
Can you check you cuda and tensorflow version? For check cuda you must use
nvcc --version. And try to Google numa mode problem

вт, 2 окт. 2018 г., 14:09 InomnipotentComedy <notifications@github.com>:

**Comment by InomnipotentComedy** [comment]
Thank you very much! I followed your instruction step by step and solved the problem. This issue will be closed.

**Comment by 3196887235** [comment]
i want to know how you do,i meet the same errors,and my cuda and tensorflow version is ok,i do not how deal with it? thank you
