### ISSUE TITLE
Note: VTK for Python 3 is available in Anaconda

### ISSUE THREAD

**Issue by ktkirk** [lmb-freiburg/demon#6]
Just to note VTK for Python 3 is available with [Anaconda](https://www.continuum.io/why-anaconda) 

$ conda search vtk
Fetching package metadata ...........
pyvtk                        0.5.18                   py27_0  conda-forge     
                             0.5.18                   py35_0  conda-forge     
                             0.5.18                   py36_0  conda-forge     
vtk                          7.0.0                    py27_0  conda-forge     
                             7.0.0                    py35_0  conda-forge     
                             7.0.0                    py27_1  conda-forge     
                             7.0.0                    py35_1  conda-forge     
                             7.0.0                    py27_2  conda-forge     
                             7.0.0                    py35_2  conda-forge     
                             7.1.0                    py27_0  conda-forge     
                             7.1.0                    py35_0  conda-forge     
                             7.1.0                    py27_1  conda-forge     
                             7.1.0                    py35_1  conda-forge     
                             7.1.0                    py27_2  conda-forge     
                             7.1.0                    py35_2  conda-forge     
                             7.1.0                    py27_3  conda-forge     
                             7.1.0                    py35_3  conda-forge     
                             7.1.0                    py36_3  conda-forge     
                             7.1.0                    py27_4  conda-forge     
                             7.1.0                    py35_4  conda-forge     
                             7.1.0                    py36_4  conda-forge     
                             5.10.1                   py27_0  defaults        
                             5.10.1                   py27_1  defaults        
                             6.3.0                    py27_0  defaults        
                             6.3.0                    py27_1  defaults

**Comment by benjaminum** [comment]
Thank you for this information!

We updated the project README.
