### ISSUE TITLE
undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

### ISSUE THREAD

**Issue by PANCHEN-AMA** [lmb-freiburg/demon#67]
Could anybody help me with this error?
I want to run demon example. Compile was succeed. When I imported lmbspecialops in python. This error happened.

Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lmbspecialops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panchen/Project/demon/lmbspecialops/python/lmbspecialops.py", line 30, in <module>
    lmbspecialopslib = tf.load_op_library(_lib_path)
  File "/home/panchen/.pyenv/versions/anaconda3-5.0.1/envs/demon/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/panchen/Project/demon/lmbspecialops/build/lib/lmbspecialops.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

I'm using Ubuntu 18.04 | tensorflow-gpu 1.10.0 | cmake 3.7.1 | gcc 4.8.5. And I didn't build tensorflow from source.

**Comment by tianjing96** [comment]
Hello,I just have met the same problem.And the environment is the same as yours.Finally,I turned my version of cuda into cuda8.0 ,and the problem has been solved.

**Comment by PANCHEN-AMA** [comment]
@tianjing96 Thank you! I tried to update anaconda from 3-5.0.1 to 3-5.3.1. And the problem is solved.
