### ISSUE TITLE
Bug in depth2normal.cu

### ISSUE THREAD

**Issue by pengwangucla** [lmb-freiburg/demon#7]
HI Benjamin,

Bug in your depth2normal code ? I recently use your depth2normal code and find the tensorflow implementation.

```c++
    const T cx = 1/(intrinsics[4*z+2]*x_size);
    const T cy = 1/(intrinsics[4*z+3]*y_size);

```
you have cx, cy as inverse of the input. I think it might be a bug since when we compute cx, cy, we do not need to inverse it.

**Comment by benjaminum** [comment]
moved to https://github.com/lmb-freiburg/lmbspecialops/issues/1
