### ISSUE TITLE
How to create 3D point clouds with multi-images?

### ISSUE THREAD

**Issue by JackHenry1992** [lmb-freiburg/demon#8]
Hi, I have test your vtk code and create point clouds of one single image (fr3_teddy).
**But I cannot get quality result if input multi-images (use your rgbd_test.h5 file).**

Have you reconstruction 3D point clouds use multi-images?
 Can you send me your reconstruction code if you have done this work? 
My email address 1005715562@qq.com. Thks a lot

**Here are my test results:**

- **1. gts pointclouds use gts_rt and gts_depth**

![image](https://user-images.githubusercontent.com/9390228/27478656-1a5a3f36-5843-11e7-8c93-f801d85fa4fb.png)

- **2.DeMoN esti. results** 
![image](https://user-images.githubusercontent.com/9390228/27478840-f2c9df34-5843-11e7-91fc-ae85c924ce4c.png)

Are there some errors in my test?

**Comment by benjaminum** [comment]
We don't have code for aligning multiple images.

The visualization code always puts the first camera at the origin.
Could this be the problem in your visualizations?

**Comment by nikolausmayer** [comment]
Closed due to inactivity.
